## a=0, b=1, etc.
# Encryption: C = (P + K) mod 26
# Decryption: P = (C - K) mod 26
# Each individual character is shifted differently. 

from collections import Counter
import matplotlib.pyplot as plt
import numpy as np

# i mod key_len =- 0, 1, 2, ..., n-1
# this way get all the streams to analyse

cipher = "MIGFBJTSZQVUOHYUVUOFUBTOVXTUXRTUTLXIVXRTZIIYROSZTTHMIGFJTXTSXRTHBHTXQTBPRXGILXVUTDCTHXTHPJBLRXUBPUOGLMIGZBHBHPOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRBLXOZJTOHSXRTVIJJIABHPIHTOUTHIXUTVTUUTSXIBHXRTXTWXROEBHPZTTHMIGFBJTSLBHMTXRTMIGFJTXBIHIVXRTZIIYXRTIHTRCHSUTSOHSHBHTGILXVUTDCTHXTHPJBLRSBPUOGLMIGFBJTSVUIGOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRTIUBPBHOJVBPCUTLATUTGOSTABXROXQFTAUBXTUOHSXRTHJBHTLOUUIALIUMBUMJTLATUTOSSTSXRBLVBJTUTFUISCMTLXRTGOLATJJOLBLFILLBZJTOLFJOBHXTWXFJTOLTLTTXRTRXGJETULBIHBVQICABLRXILTTXRTVBPCUTLABXROJJIVXRTBUSTXOBJLGBHIUMIUUTMXBIHLLCMROLUTGIEBHPTWXUOLFOMTLIUFCHMXCOXBIHIUOSSBHPGBLLBHPLFOMTLIUFCHMXCOXBIHIUSBOMUBXBMOJGOUYLATUTGOSTABXRICXHIXTOUMROBMOHSBHMIHLBLXTHXLFTJJBHPAOLUTXOBHTSBHXAIFJOMTLXRTHCGZTUIVOUTVTUTHMTSVBPCUTAOLMIUUTMXTSPUOGGOUOHSLFTJJBHPATUTIHJQMIUUTMXTSOLBHXRTVIJJIABHPJBLXIVHIXOZJTMROHPTLBHMROFXTUBBBATBXOJBMBKTSXRTVBULXIMMCUUTHMTIVGOPBMLDCOUTZTMOCLTBXLTTGTSJBYTXRTOCXRIULBHXTHXBIHBHXRTLOGTMROFXTULOBSZTMJIMYABLTAOLMIUUTMXTSXILOBSXIZTMJIMYABLTLIGTMIUUTMXBIHLATUTGOSTXIXRTTWTUMBLTLBHIUSTUXIUTMXBVQXRTLFTJJBHPBHXRTBUFJOBHXTWXLIUBHIHTMOLTXIUTLIJETOHBHMIHLBLXTHMQBHBXLYTQBHTWTUMBLTLTETHJTXXTULATUTGBLLBHPXRTCHMIUUTMXTSMUQFXIPUOGBLEBHLMVTOTIIRLTVRJTRCHLXHMJXLJMBOTLRURLBUTUGXLTXTFSXIBHGUXXRXXJUCZTATABLRXIXROHYXRTOHIHQGICLFUIIVUTOSTULARIEIJCHXTTUTSOXXRTZUBXBLRHOXBIHOJMBFRTUMROJJTHPTAAAMBFRTUMROJJTHPTIUPXRTAIUSMUQFXIPUOFRQFUIFTUJQLFTOYBHPTGZUOMTLXRTTHXBUTVBTJSIVLTMUTXAUBXBHPARBJTXROXZUOHMRIVXRTLCZNTMXSTOJBHPABXRXRTLIJCXBIHOHSUTOSBHPIVMUQFXBMGTLLOPTLBLPTHTUOJJQUTVTUUTSXIOLMUQFXOHOJQLBLAIUYLIHXRTLCZNTMXIVLTMUTXAUBXBHPOUTMIGFOUOXBETJQHCGTUICLBVHIXOJAOQLTOLBJQOEOBJOZJTZCXAIUYLSTEIXTSFCUTJQXIXRTOHOJQLBLIVLCMRAUBXBHPOHSXRTLIJEBHPIVBXLMUQFXIPUOGLROETCHXBJUTMTHXJQZTTHLIUOUTOLXIZTOJGILXHIHTWBLXTHXVIUXRTPTHTUOJUTOSTUXISOQATROETXAIFOUXBMCJOUJQTWMTJJTHXAIUYLZCXZIXRBHVIUTBPHJOHPCOPTLMICULSTMUQFXIPUOFRBTZQPTHTUOJGOUMTJPBEBTUPTOHSGOHCOJTSBMUBXXIPUOVBOZQPTHTUOJJCBPBLOMMIBHTHPJBLRATVBHSOGIUTTJTGTHXOUQAIUYXRTLIJCXBIHIVMISTLOHSMBFRTULZQJICBLMLGOHLVBTJSGOMJTRILTJIHSIHARBMRXRTAUBXTUROLZTTHXIJSBLXIZTOVBULXEIJCGTOLXIOGTUBMOLMIHXUBZCXBIHATLTTGXIVBHSIHJQLGOJJZIIYLLCMROLMIJIHTJFOUYTURBXXLOZMIVLTMUTXAUBXBHPMIETUBHPXRUTTMBFRTULIUMIJIHTJRIQOUSJTQLQOUSJTQPUOGLXRTUTOUTRIATETUGOHQAIUYLARBMRSTOJGILXBHXTUTLXBHPJQABXRXRTOHOJQLBLOHSSTMUQFXGTHXIVLIGTIHTFOUXBMCJOUMBFRTUGILXIVXRTLTOUTLRIUXAIUYLFCZJBLRTSBHGOPOKBHTLIUBHMIUFIUOXTSBHXIZIIYLIVOPTHTUOJHOXCUTOHSHTOUJQOJAOQLXRTIHTMBFRTUSTOJXABXRBLXROXXQFTIVLBGFJTLCZLXBXCXBIHARBMROFFTOULABXRLTFOUOXTSAIUSLBHXRTFCKKJTLTMXBIHIVICUMCUUTHXGOPOKBHTLOHSHTALFOFTULIHTATJJYHIAHPTGIVMUQFXOHOJQLBLTDCOJXIOHQGISTUHLFTMBGTHMOHZTVICHSBHXRTLXIUQXRTPIJSZCPZQTSPOUOJJOHFITXRBLXIISTOJLABXRXRTLBGFJTLCZLXBXCXBIHMBFRTUNCLXUTVTUUTSXIZCXMIETULOMOLTBHARBMRAIUSSBEBLBIHLOUTOZLTHXFITROLOJLIJTVXCLOHTLLOQMOJJTSMUQFXIPUOFRQUILOUBIMOHSTJOLUTMTHXZIIYXRTGBJBXOUQMBFRTUIVMIGGOHSOHXZOKTUBTLLRIALXRTCHUOETJBHPIVIHTFOUXBMCJOUMUQFXIPUOGARBMRVIUGOHQQTOULROSZOVVJTSXRTZTLXTVVIUXLIVOJJOGOXTCULOHSBXBLUOXRTULCLFTMXTSIVLIGTVTAARIATUTHIXOGOXTCULXRTZIIYMIHXOBHLOMROFXTUIHPTHTUOJMUQFXOHOJQLBLOHSOJLILIGTMUQFXIPUOGLVIULIJCXBIHLTMUTXOHSCUPTHXZQVJTXMRTUFUOXXBLFUBGOUBJQORBLXIUQIVLTMUTXAUBXBHPOGILXBHXTUTLXBHPIHTZQXRTAOQZCXMIHXOBHLOJLIOHCGZTUIVTWOGFJTLIVMUQFXOHOJQLBLBXOJLILRIALOXOZJTARBMRXRTAUBXTUROLHTETUZTVIUTLTTHBHFCZJBLRTSVIUGOJBLXIVTHPJBLRXUBPUOGLXRUTTJTXXTULTDCTHMTLOHSXRTVUTDCTHMQABXRARBMRXRTQOUTCLTSBHXRTJOHPCOPTIXRTUTWOGFJTLIVSTMUQFXGTHXGOQZTVICHSBHXRTGOMZTXRXUOHLJOXBIHIVJOHPBTLPTHBOJJBXXJTZIIYSTJOMUQFXIPUOFRBTXRTOFFTHSBWXIXRBLXUOHLJOXBIHMIHXOBHLXRTMIETXTSFJOQVOBUSTGIHLXUOXBIHFUTFOUTSZQJBTCXTHOHXMIGGOHSTUAALGBXRIVXRTCHBXTSLXOXTLHOEQNCLXARQLIOZLIUZBHPOLCZNTMXROLZTTHLIHTPJTMXTSBHOAIUJSVCJJIVFCKKJTJIETULBLROUSXICHSTULXOHSTLFTMBOJJQLBHMTXRTOHOJQXBMAUBXTUBHOSSBXBIHXITHXTUXOBHGTHXROLLIGTXRBHPXIIVVTUIVOGIUTLTUBICLHOXCUT"
alphabet=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

bigraphs = {
    "th": 5532,
    "he": 4657,
    "in": 3429,
    "er": 3420,
    "an": 3005,
    "re": 2465,
    "nd": 2281,
    "at": 2155,
    "on": 2086,
    "nt": 2058,
    "ha": 2040,
    "es": 2033,
    "st": 2009,
    "en": 2005,
    "ed": 1942,
    "to": 1904,
    "it": 1822,
    "ou": 1820,
    "ea": 1720,
    "hi": 1690,
    "is": 1660,
    "or": 1556,
    "ti": 1231,
    "as": 1211,
    "te": 985,
    "et": 704,
    "ng": 668,
    "of": 569,
    "al": 341,
    "de": 332,
    "se": 300,
    "le": 298,
    "sa": 215,
    "si": 186,
    "ar": 157,
    "ve": 148,
    "ra": 137,
    "ld": 64,
    "ur": 60,
}

trigraph = {
    "THE": 1.81, "AND": 0.73, "ING": 0.72, "ENT": 0.42, "ION": 0.42,
    "HER": 0.36, "FOR": 0.34, "THA": 0.33, "NTH": 0.33, "INT": 0.32,

    "ERE": 0.31, "TIO": 0.31, "TER": 0.30, "EST": 0.28, "ERS": 0.28,
    "ATI": 0.26, "HAT": 0.26, "ATE": 0.25, "ALL": 0.25, "ETH": 0.24,

    "HES": 0.24, "VER": 0.24, "HIS": 0.24, "OFT": 0.22, "ITH": 0.21,
    "FTH": 0.21, "STH": 0.21, "OTH": 0.21, "RES": 0.21, "ONT": 0.20
}

cipher = cipher.lower()
# [index+1] -- to find the corresponding. plain+key % 26 - 1, something. then decr, 

def stream(cipher, key_len):
    streams = [""] * key_len
    index = 0

    for c in cipher:
        streams[index] += c
        index = (index + 1) % key_len
    # print(streams)
    return streams
    

# test all offsets and count matches. 
def offset(cipher):
    n = len(cipher)
    counts = []
    
    # set the n to maximum key length, maybe 50?
    for shift in range(1, 100):
        count = 0

        # cipher[i] is the shifted cipher
        # cipher[i+shift] is the original one. 
        # c0 c1 c2 c3 c4 | original starts on the shift index
        #    c0 c1 c2 c3 | shifted starts on index 0 of original.
        # we end on n-shift
        for i in range(n-shift):
            if cipher[i] == cipher[i+shift]:
                count += 1
        counts.append(count)

    print(counts)
    return counts

def print_offset(counts):
    plt.figure(figsize=(50, 4))
    plt.bar(range(len(counts)), counts)
    plt.xticks(range(len(counts)))

    plt.show() 

def freq(cipher):
    cipher = Counter(cipher).most_common()
    
    return cipher


def frequency(cipher):
    cipher = Counter(cipher).most_common()
    print(cipher)

    freqEnglish = {'e': 0.12702, 't': 0.09056, 'a': 0.08167, 'o': 0.07507, 'i': 0.06966, 'n': 0.06749, 
                's': 0.06327, 'h': 0.06094, 'r': 0.05987, 'd': 0.04253, 'l': 0.04025, 'c': 0.02782,
                'u': 0.02758, 'm': 0.02406, 'w': 0.02360, 'f': 0.02228, 'g': 0.02015, 'y': 0.01974, 
                'p': 0.01929, 'b': 0.01492, 'v': 0.00978, 'k': 0.00772, 'j': 0.00153, 'x': 0.00150,
                'q': 0.00095, 'z': 0.00074}

    letters = list(freqEnglish.keys())
    frequencies = list(freqEnglish.values())

    cipher_letters = [obj[0] for obj in cipher]
    cipher_frequencies = [obj[1] for obj in cipher]

    fig, axes = plt.subplots(2, 1, figsize=(20, 4))

    axes[0].bar(letters, frequencies, color='skyblue')
    axes[0].set_title('English Standard Frequency', fontsize=10)
    axes[0].set_xlabel('Letters', fontsize=10)
    axes[0].set_ylabel('Frequency', fontsize=10)
    axes[0].grid(axis='y', alpha=0.3)

    # Plot 2: Vowels only (sorted)
    axes[1].bar(cipher_letters, cipher_frequencies, color='lightcoral')
    axes[1].set_title('Stream 7', fontsize=10)
    axes[1].set_xlabel('Letters', fontsize=10)
    axes[1].set_ylabel('Frequency', fontsize=10)
    axes[1].grid(axis='y', alpha=0.3)

    plt.tight_layout()  # Adjust spacing between subplots
    plt.show()

def decrypt(key, cipher):
    plaintext = ""  

    for c in cipher:
        plaintext += alphabet[(alphabet.index(c)-key) % 26]
    return plaintext

def vig(keys, cipher):
    plaintext = ""  
    key_index = 0

    for c in cipher:
        plaintext += alphabet[(alphabet.index(c)-alphabet.index(keys[key_index % 6])) % 26]
        key_index += 1

    return plaintext

def ic(stream):
    counts = Counter(stream)
    length = len(stream)
    ic = 0.0

    for c in counts:
        ic += (counts[c] / length) * (counts[c] - 1) / (length - 1)

    # print(ic)
    return ic

def find_alph(a, b):
    return (alphabet[(alphabet.index(a) - alphabet.index(b)) % 26])


def mono(cipher, key):
    plaintext = ""
    for c in cipher:
        plaintext += key[alphabet.index(c)]

    return plaintext

def digram(cipher):
    digram = {}

    for i in range(len(cipher) - 1):
        di = cipher[i:i+2]

        if not di in digram:
            digram[di] = 1
        else:
            digram[di] += 1

    return digram

def trigram(cipher):
    trigram = {}

    for i in range(len(cipher) - 2):
        di = cipher[i:i+3]

        if not di in trigram:
            trigram[di] = 1
        else:
            trigram[di] += 1

    return trigram

def print_di(digram, digraph):
    ci = list(digram.keys())[:25]
    civ = list(digram.values())[:25]

    dig = list(digraph.keys())[:25]
    digv = list(digraph.values())[:25]


    fig, axes = plt.subplots(2, 1, figsize=(20, 4))

    axes[0].bar(ci, civ, color='skyblue')
    axes[0].set_title('Ci Digraph Frequency', fontsize=10)
    axes[0].set_xlabel('Letters', fontsize=10)
    axes[0].set_ylabel('Frequency', fontsize=10)
    axes[0].grid(axis='y', alpha=0.3)

    # Plot 2: Vowels only (sorted)
    axes[1].bar(dig, digv, color='lightcoral')
    axes[1].set_title('Eng Digraph Freq', fontsize=10)
    axes[1].set_xlabel('Letters', fontsize=10)
    axes[1].set_ylabel('Frequency', fontsize=10)
    axes[1].grid(axis='y', alpha=0.3)

    plt.tight_layout()  # Adjust spacing between subplots
    plt.show()




digram = digram(cipher)
print(dict(sorted(digram.items(), key=lambda item: item[1], reverse=True)))
print_di(dict(sorted(digram.items(), key=lambda item: item[1], reverse=True)), bigraphs)

trigram = trigram(cipher)
print(dict(sorted(trigram.items(), key=lambda item: item[1], reverse=True)))
print_di(dict(sorted(trigram.items(), key=lambda item: item[1], reverse=True)), trigraph)
# map different key letter, maybe iterate a list of possible. try what works.
# bruteforce? not nec.

# could bruteforce different combinations + digraph/trigraph -- to see if there are any clues

key = "pgvniceyxjrobhlmtqausrfwkz"
# e-> i
# t -> u?
# aonsihr -> plxhayq
# dlcu -> novs

# the -> xrt. -> t -> x, h -> r, e -> t

# n -> h

# print(mono(cipher, key))

"""
        
total_counts = offset(cipher)
print_offset(total_counts)

streams = stream(cipher, 26)
coinc = 0
for s in streams:
    coinc += ic(s)
    print("Average: ", coinc/len(streams))


for s in streams:
    print(freq(s))
    frequency(s)



for i in range(2, 50, 1):
    streams = stream(cipher, i)

    print("Key Size:", i)

    frequency(streams[0])
    frequency(streams[1])


key_sizes = [41, 37, 26, 46, 14, 49]

print("IC of entire cipher: ", ic(cipher))

streams = stream(cipher, 41)
for s in streams:
    print(freq(s))
    frequency(s)



for k in key_sizes:
    streams = stream(cipher, k)
    print("Key size: ", k)

    for s in streams:
        print("  key letter")
        counts = freq(s)
        print(find_alph(counts[0][0], "e"))
        print(find_alph(counts[1][0], "t"))
        print(find_alph(counts[2][0], "a"))
        print(find_alph(counts[3][0], "o"))
        print(find_alph(counts[4][0], "i"))

"""
# frequency(streams[6])



keys = "semper"

#print(vig(keys, cipher))


"""
seed=123436  key=KASISKI  recovered=KASISKI  wrong=0  PASS
seed=123436  key=OZMSTVPRBNYJGHIFDULXCEAWQK  recovered=OZMSTVPRBNYJGHIFDULXCEAWQK  wrong=0  PASS
=== CIPHERTEXT CHALLENGE ===

--- Ciphertext 1 ---
DHWKZKVMEKIJOBRALBZSAVELBWBCGILPADAVOONJOYEEFKQBMZRWAWXBCYAVKYUOSMKZPWBMSBAYVKSSTDICVLQMLDGOTUEADPPOMZNYEOLKBWXBKTADWVGSSGTSDMNWWIJOVYWAVSZWCILQGXBYAHXDIXYIFBWBVYAFLLRQCWWUSILYBQZWDCBNAVYDWDHWKJIXDOYZSWIXDEIJUQXGXWJKBDEFBAYVOAUPSZXOAJIFMMYFWIURAEPHWKOLFOOMDDPSSAAMCCKLDGVYVOBQKABKVIFOWKKROFMOSBRAHMFMQVMSZCSVPIYIKWIVLDMLDMBVZIKCMBVWLLRMCAEMHEZZOKMSXLKFWEKOZSADVMWJORKPSFMLEWVSNLODXWJMWXVWVAOVMEGNJONORWVUOVYWDMLEAOXSUAXMPIYILKEKTUPAXODHWAEKTVVKEWPQXDSNSSZVYMVAPWBMVQKDZSBMBAYVYFNWOOTCEPKWZBPOJBZBMOLGVYCMQMWVLCJOGAVFSVQRWAHOKDINMDIIDTZMLRBRAFLLRTOTLMJCNYRUWFFMXIWVUOBREKMZKDOBWMFMWZIWLGEBKTTBZOBGOGNLRMCEOPAMPKRWTGXOORSVVDPORWNGBMWOKBDSSOLQBGMWXTSQFKBVESALYVOOXBZOUSSKQFQDYWWTKKZOBGBZPWENVBGRIFEAVUVCNEVHSXLTOXBZOAOTOWDOBDEJARSAYNWEZSKRWSAHBMFIGCKVGNIKKSBLODXZGWBREUMFDZKLKMUDQYNGNLRMRIYPXBMAUWVUIOBOMXVEZSNYWMBXBEDQESVKRQQFFMCTAOSDQYNWFSWQXIFOADIQAAVLYUKKWAMBMGEXQFNQDNGESCINOMJDOJOTOMWXBGOKCHZWCEVDGGMVSSVVRIFIFOLGWKDVQLSWXADKGXBKCLAOSBRSMXHYAODNWOOTCPGQFDMBSSVVLCDJOMXSVNHSAFODORUWFDIMTWLSXGCUHXGCMNVGEWVQDRWDWBAOSOQLRICUHXGCMNCGVKYVKNLIFNAROOASCUECZDSBQOTQIKMWELVJWOFZEUBWNWPADMLDMBAHXWKZSNYWFVGDHJMWDQWEKNAQCBESDNFDFVNDNFLZRWTAWQXAJGSCAEMHBAYVCYLMWKPYALPGOBROUWJBMMTAWFCGDOGIZOIDHWWLRMDOYWSRMKDLPWYBREJBZOIMCWXLKVMEGNBZZYVALWCNSVWWXDPOVGEWVAGILPXBMAUWVUSMCOXIFNIDOLIDYNYULWXKVOXHMUDMNIFIDYVQEJKJIXDOYZSWEOSZWMVLZRGJSLTILGWCPWBTZMKSFDHNWOOTKMGVYDPYSWTWDBORKPSFQXGSXHBWHIEILOTITZMUYZBEUBXBMAUWVUINYREICSVQUHBZOMHPWKLOLKSLWLRMZRWAWXBMAKMOOAROMTVRIFEFWLBWEBDMKOTOCLQFQQDFJWEDPOFADWVMDTWZKOOWEFBSDJLULBZSAGOMTVMIESWCKDWCPGBSVAYTZMKRWBTOWJNQXWZQURQDIKCKOLKNVWMBQWMWLAKBOCGVUOZXIKBZKBYFKXGDBSNYDGGMVSGVDIBRRGCYRBREAZCXWGNUPSBIMTWZACBSCKIKFWGEDAOOESLDIKCCWELPWXBRALBZOTKSLDGGMVCSVFYBLEXWMXLDHWVWHBCTWXVOUKNVALRIDWWIKCQQNLWLRMWOKBXBMAUWVLYNDHWAMZXYSWLNYEOLKBZODKLMMWGPSCZPSZXONKBGLMKWJWFQICSMUHDQYNUWFMMBNAVYDPSSABEKGLEOMDVBYRWXWKBREJMKYUOTZQFQERIUPZKAKLJMSNGLEWVKKQNIFLWKTSNYEADPDHWAAWXVEKBGPKBYHBGQZKMKBZOZOIKWXDMXAKPGBBNELWMBQXTGBJSIVAFLWBZYRSTKYBRESDWBIQEVMUBGZTGZSMKESLWEOLDOLPWGWBKSVVPCVLQIOKZOOXEZKBREEIQOFZEUBXBWWOFTQVMDTWZKYNDEPBOSTVUKCSVTIPSCKOIDTZQKZWSNLIFNUKKWAGWMPUJBZOZYBKMJFIDIGVKLMPOJMXSTVIFOAXIXYGNZSACUTALSBETAWFCPYWWDWBBREJMACDKLMMWFMXIFBZOUKKAVYYNGRGVYCCLSLQLEBSOFALRMKCLCSVXVAUQFQWPSMXHYAODHTSSVDEPBNKTEEKQFDPOIJAMZXYSWLHYASTAWFCXETKBZOXVAAVLOFDPGAKSJSLABAOALEXWJOCCIFDACCKLXWJWKKUKQFQCCTGVGDMOAKQDIBROKMNOZIPGQFDAPOJEZSKRTZMWHXORAMFMMNDWKJIXDOJMPKUSNWAAXINVSVUOIDCLPWXEOHSDWWINEGCJCCLSLQLEBSOFAOOPKVWIKCCWEVBZKBDHWUGCBPRWYMOVDVGEWVLSSJMHBMCEFBAXOOHSDAXOXOLMVDPOVNLAQZKMKLKFLFSOMZKDOSWTWMBODKZSDPORLPSXDKSLPWCCLSLQLEBOFGZSZZOFWZJSVQAVQYBIWOSLKDWKDAOJKUKONLLRQCLWINOADHWDGGMVOXAWMWXDXZWACONUGNDWBEHZWCMXTGBZSAGIDTUKCCELPWDPSRVWXDPOVNLAQZKMKDKDWBEHZWCMXTGMFYBPRWYMOVDBMBTOBDEJBZKVDHWLAQZKMSWHBMFIGCKVGWEFBAYVODBBZOVZRGJSLTIRWXJOAONLAAKVNUEIQBMZRWAWXBIAKBGMWXSGVSXBCWWPSFMKSKQYXMNTZMNKTEELBGDPOMGALPZOQMMFDWXEJIFNBREJMZKALEWVFYLSFXQUETDYAVANMXTANQSVQHAVLRMVELBWBSGHAKZDPBEWBAWMCHSAXYTVOOMVBJETGCJZZOSWVLMZIPLWYBIWIKBGYAROJBLYXBONQVOIXYUTWKZNIKBAXKDIGVSWWXGDMLDMBSOPAMPWIYPLBMZRWAWXBXRKEADPDHWAWFMXSMJKDQDULQGXAWAVMSCAROOVSDKXOLQUOPYWICAMSVYABTOKYMWAHYACITTWDWCPGBLRMSNUWFQZEILGGPAOQMMFMMCTZWEYZOTZIFYVMEAVSCPYRLBWHBGHAKZMWXTSQFCVYTSAAXOVEGKUEZBEFKWYNREGZZKVYTAKWKOKIFILNPYWICAMSVYLPWWMBEWFURIXGAVYYNDHWDSVCOSWIFNWGIDTTBQXGGCLGWBDKCYQMCTAWFCIDELPWPQBSLTAXMYFLPWMZIPLWYBIWIKZWZMKTWLSCQDWGCDNIZPWIJKNDEJBZOUKKAVYYNDHAAWHKRAFOWDPOBWOAXVSNYWXDPOMWAKKOOCSVSVUYSLJWBMKDLPWPQBSLEGBLKPHMSBADOTMFYBSFQNMBVSSZQFQBGOFMOCCLSLQLEBOSLPJOMWOJMUKVLEXCJXQCHWLAXBREKCYQMCTWLKOYEEFKWDWQOSPWKLGILPSXLREJMLRMGOJLOSBRWGCDNJOTJQWNQXAFGUKAOBWKSEAOILQKKKYMEWFGWBDSVVLMMAMAWDPOFJMIEMXCQWXDPOLWBLOZZIKAMQOOSLQNOWPWSZJSDODSBLRQCPGQFDEOBWOAXBYNGBAMMZALBWBVCPGALZWXEUWMXKSLSKUYCXTEILDMBAFLKYWXSGBZKBDHWZWCBYFLPWCWVULQGXQCLSZYOTIAEILDMBOXNAVTSNYQFPZKMWEGBSSNLPWQQFEFMPKUZLWQLGWELVIDCWLEFWLSKODLPSDNKNVVZKDORWAMVBODXZGWZOCAXJYKKLWVUSXREJUWXBDHAAEKGXOLJWDPOCSAWGQDHGBZOZVELBWBALULQLZZOSWVLCIZOKAALQVILGORQMHAASVEKYKEWVTGOJBZSVFEKBAQIDIFOSLKNEXOZSRULEVGZYBSLCNGFIZSITLKMDVMWPNCGYMZRKSIGRBXSUDDTLRMNIYZSWAYLMBAYVWELPGN

--- Ciphertext 2 ---
MIGFBJTSZQVUOHYUVUOFUBTOVXTUXRTUTLXIVXRTZIIYROSZTTHMIGFJTXTSXRTHBHTXQTBPRXGILXVUTDCTHXTHPJBLRXUBPUOGLMIGZBHBHPOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRBLXOZJTOHSXRTVIJJIABHPIHTOUTHIXUTVTUUTSXIBHXRTXTWXROEBHPZTTHMIGFBJTSLBHMTXRTMIGFJTXBIHIVXRTZIIYXRTIHTRCHSUTSOHSHBHTGILXVUTDCTHXTHPJBLRSBPUOGLMIGFBJTSVUIGOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRTIUBPBHOJVBPCUTLATUTGOSTABXROXQFTAUBXTUOHSXRTHJBHTLOUUIALIUMBUMJTLATUTOSSTSXRBLVBJTUTFUISCMTLXRTGOLATJJOLBLFILLBZJTOLFJOBHXTWXFJTOLTLTTXRTRXGJETULBIHBVQICABLRXILTTXRTVBPCUTLABXROJJIVXRTBUSTXOBJLGBHIUMIUUTMXBIHLLCMROLUTGIEBHPTWXUOLFOMTLIUFCHMXCOXBIHIUOSSBHPGBLLBHPLFOMTLIUFCHMXCOXBIHIUSBOMUBXBMOJGOUYLATUTGOSTABXRICXHIXTOUMROBMOHSBHMIHLBLXTHXLFTJJBHPAOLUTXOBHTSBHXAIFJOMTLXRTHCGZTUIVOUTVTUTHMTSVBPCUTAOLMIUUTMXTSPUOGGOUOHSLFTJJBHPATUTIHJQMIUUTMXTSOLBHXRTVIJJIABHPJBLXIVHIXOZJTMROHPTLBHMROFXTUBBBATBXOJBMBKTSXRTVBULXIMMCUUTHMTIVGOPBMLDCOUTZTMOCLTBXLTTGTSJBYTXRTOCXRIULBHXTHXBIHBHXRTLOGTMROFXTULOBSZTMJIMYABLTAOLMIUUTMXTSXILOBSXIZTMJIMYABLTLIGTMIUUTMXBIHLATUTGOSTXIXRTTWTUMBLTLBHIUSTUXIUTMXBVQXRTLFTJJBHPBHXRTBUFJOBHXTWXLIUBHIHTMOLTXIUTLIJETOHBHMIHLBLXTHMQBHBXLYTQBHTWTUMBLTLTETHJTXXTULATUTGBLLBHPXRTCHMIUUTMXTSMUQFXIPUOGBLEBHLMVTOTIIRLTVRJTRCHLXHMJXLJMBOTLRURLBUTUGXLTXTFSXIBHGUXXRXXJUCZTATABLRXIXROHYXRTOHIHQGICLFUIIVUTOSTULARIEIJCHXTTUTSOXXRTZUBXBLRHOXBIHOJMBFRTUMROJJTHPTAAAMBFRTUMROJJTHPTIUPXRTAIUSMUQFXIPUOFRQFUIFTUJQLFTOYBHPTGZUOMTLXRTTHXBUTVBTJSIVLTMUTXAUBXBHPARBJTXROXZUOHMRIVXRTLCZNTMXSTOJBHPABXRXRTLIJCXBIHOHSUTOSBHPIVMUQFXBMGTLLOPTLBLPTHTUOJJQUTVTUUTSXIOLMUQFXOHOJQLBLAIUYLIHXRTLCZNTMXIVLTMUTXAUBXBHPOUTMIGFOUOXBETJQHCGTUICLBVHIXOJAOQLTOLBJQOEOBJOZJTZCXAIUYLSTEIXTSFCUTJQXIXRTOHOJQLBLIVLCMRAUBXBHPOHSXRTLIJEBHPIVBXLMUQFXIPUOGLROETCHXBJUTMTHXJQZTTHLIUOUTOLXIZTOJGILXHIHTWBLXTHXVIUXRTPTHTUOJUTOSTUXISOQATROETXAIFOUXBMCJOUJQTWMTJJTHXAIUYLZCXZIXRBHVIUTBPHJOHPCOPTLMICULSTMUQFXIPUOFRBTZQPTHTUOJGOUMTJPBEBTUPTOHSGOHCOJTSBMUBXXIPUOVBOZQPTHTUOJJCBPBLOMMIBHTHPJBLRATVBHSOGIUTTJTGTHXOUQAIUYXRTLIJCXBIHIVMISTLOHSMBFRTULZQJICBLMLGOHLVBTJSGOMJTRILTJIHSIHARBMRXRTAUBXTUROLZTTHXIJSBLXIZTOVBULXEIJCGTOLXIOGTUBMOLMIHXUBZCXBIHATLTTGXIVBHSIHJQLGOJJZIIYLLCMROLMIJIHTJFOUYTURBXXLOZMIVLTMUTXAUBXBHPMIETUBHPXRUTTMBFRTULIUMIJIHTJRIQOUSJTQLQOUSJTQPUOGLXRTUTOUTRIATETUGOHQAIUYLARBMRSTOJGILXBHXTUTLXBHPJQABXRXRTOHOJQLBLOHSSTMUQFXGTHXIVLIGTIHTFOUXBMCJOUMBFRTUGILXIVXRTLTOUTLRIUXAIUYLFCZJBLRTSBHGOPOKBHTLIUBHMIUFIUOXTSBHXIZIIYLIVOPTHTUOJHOXCUTOHSHTOUJQOJAOQLXRTIHTMBFRTUSTOJXABXRBLXROXXQFTIVLBGFJTLCZLXBXCXBIHARBMROFFTOULABXRLTFOUOXTSAIUSLBHXRTFCKKJTLTMXBIHIVICUMCUUTHXGOPOKBHTLOHSHTALFOFTULIHTATJJYHIAHPTGIVMUQFXOHOJQLBLTDCOJXIOHQGISTUHLFTMBGTHMOHZTVICHSBHXRTLXIUQXRTPIJSZCPZQTSPOUOJJOHFITXRBLXIISTOJLABXRXRTLBGFJTLCZLXBXCXBIHMBFRTUNCLXUTVTUUTSXIZCXMIETULOMOLTBHARBMRAIUSSBEBLBIHLOUTOZLTHXFITROLOJLIJTVXCLOHTLLOQMOJJTSMUQFXIPUOFRQUILOUBIMOHSTJOLUTMTHXZIIYXRTGBJBXOUQMBFRTUIVMIGGOHSOHXZOKTUBTLLRIALXRTCHUOETJBHPIVIHTFOUXBMCJOUMUQFXIPUOGARBMRVIUGOHQQTOULROSZOVVJTSXRTZTLXTVVIUXLIVOJJOGOXTCULOHSBXBLUOXRTULCLFTMXTSIVLIGTVTAARIATUTHIXOGOXTCULXRTZIIYMIHXOBHLOMROFXTUIHPTHTUOJMUQFXOHOJQLBLOHSOJLILIGTMUQFXIPUOGLVIULIJCXBIHLTMUTXOHSCUPTHXZQVJTXMRTUFUOXXBLFUBGOUBJQORBLXIUQIVLTMUTXAUBXBHPOGILXBHXTUTLXBHPIHTZQXRTAOQZCXMIHXOBHLOJLIOHCGZTUIVTWOGFJTLIVMUQFXOHOJQLBLBXOJLILRIALOXOZJTARBMRXRTAUBXTUROLHTETUZTVIUTLTTHBHFCZJBLRTSVIUGOJBLXIVTHPJBLRXUBPUOGLXRUTTJTXXTULTDCTHMTLOHSXRTVUTDCTHMQABXRARBMRXRTQOUTCLTSBHXRTJOHPCOPTIXRTUTWOGFJTLIVSTMUQFXGTHXGOQZTVICHSBHXRTGOMZTXRXUOHLJOXBIHIVJOHPBTLPTHBOJJBXXJTZIIYSTJOMUQFXIPUOFRBTXRTOFFTHSBWXIXRBLXUOHLJOXBIHMIHXOBHLXRTMIETXTSFJOQVOBUSTGIHLXUOXBIHFUTFOUTSZQJBTCXTHOHXMIGGOHSTUAALGBXRIVXRTCHBXTSLXOXTLHOEQNCLXARQLIOZLIUZBHPOLCZNTMXROLZTTHLIHTPJTMXTSBHOAIUJSVCJJIVFCKKJTJIETULBLROUSXICHSTULXOHSTLFTMBOJJQLBHMTXRTOHOJQXBMAUBXTUBHOSSBXBIHXITHXTUXOBHGTHXROLLIGTXRBHPXIIVVTUIVOGIUTLTUBICLHOXCUT
"""
