## a=0, b=1, etc.
# Encryption: C = (P + K) mod 26
# Decryption: P = (C - K) mod 26
# Each individual character is shifted differently. 

from collections import Counter
import matplotlib.pyplot as plt
import numpy as np

# i mod key_len =- 0, 1, 2, ..., n-1
# this way get all the streams to analyse

cipher = "MIGFBJTSZQVUOHYUVUOFUBTOVXTUXRTUTLXIVXRTZIIYROSZTTHMIGFJTXTSXRTHBHTXQTBPRXGILXVUTDCTHXTHPJBLRXUBPUOGLMIGZBHBHPOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRBLXOZJTOHSXRTVIJJIABHPIHTOUTHIXUTVTUUTSXIBHXRTXTWXROEBHPZTTHMIGFBJTSLBHMTXRTMIGFJTXBIHIVXRTZIIYXRTIHTRCHSUTSOHSHBHTGILXVUTDCTHXTHPJBLRSBPUOGLMIGFBJTSVUIGOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRTIUBPBHOJVBPCUTLATUTGOSTABXROXQFTAUBXTUOHSXRTHJBHTLOUUIALIUMBUMJTLATUTOSSTSXRBLVBJTUTFUISCMTLXRTGOLATJJOLBLFILLBZJTOLFJOBHXTWXFJTOLTLTTXRTRXGJETULBIHBVQICABLRXILTTXRTVBPCUTLABXROJJIVXRTBUSTXOBJLGBHIUMIUUTMXBIHLLCMROLUTGIEBHPTWXUOLFOMTLIUFCHMXCOXBIHIUOSSBHPGBLLBHPLFOMTLIUFCHMXCOXBIHIUSBOMUBXBMOJGOUYLATUTGOSTABXRICXHIXTOUMROBMOHSBHMIHLBLXTHXLFTJJBHPAOLUTXOBHTSBHXAIFJOMTLXRTHCGZTUIVOUTVTUTHMTSVBPCUTAOLMIUUTMXTSPUOGGOUOHSLFTJJBHPATUTIHJQMIUUTMXTSOLBHXRTVIJJIABHPJBLXIVHIXOZJTMROHPTLBHMROFXTUBBBATBXOJBMBKTSXRTVBULXIMMCUUTHMTIVGOPBMLDCOUTZTMOCLTBXLTTGTSJBYTXRTOCXRIULBHXTHXBIHBHXRTLOGTMROFXTULOBSZTMJIMYABLTAOLMIUUTMXTSXILOBSXIZTMJIMYABLTLIGTMIUUTMXBIHLATUTGOSTXIXRTTWTUMBLTLBHIUSTUXIUTMXBVQXRTLFTJJBHPBHXRTBUFJOBHXTWXLIUBHIHTMOLTXIUTLIJETOHBHMIHLBLXTHMQBHBXLYTQBHTWTUMBLTLTETHJTXXTULATUTGBLLBHPXRTCHMIUUTMXTSMUQFXIPUOGBLEBHLMVTOTIIRLTVRJTRCHLXHMJXLJMBOTLRURLBUTUGXLTXTFSXIBHGUXXRXXJUCZTATABLRXIXROHYXRTOHIHQGICLFUIIVUTOSTULARIEIJCHXTTUTSOXXRTZUBXBLRHOXBIHOJMBFRTUMROJJTHPTAAAMBFRTUMROJJTHPTIUPXRTAIUSMUQFXIPUOFRQFUIFTUJQLFTOYBHPTGZUOMTLXRTTHXBUTVBTJSIVLTMUTXAUBXBHPARBJTXROXZUOHMRIVXRTLCZNTMXSTOJBHPABXRXRTLIJCXBIHOHSUTOSBHPIVMUQFXBMGTLLOPTLBLPTHTUOJJQUTVTUUTSXIOLMUQFXOHOJQLBLAIUYLIHXRTLCZNTMXIVLTMUTXAUBXBHPOUTMIGFOUOXBETJQHCGTUICLBVHIXOJAOQLTOLBJQOEOBJOZJTZCXAIUYLSTEIXTSFCUTJQXIXRTOHOJQLBLIVLCMRAUBXBHPOHSXRTLIJEBHPIVBXLMUQFXIPUOGLROETCHXBJUTMTHXJQZTTHLIUOUTOLXIZTOJGILXHIHTWBLXTHXVIUXRTPTHTUOJUTOSTUXISOQATROETXAIFOUXBMCJOUJQTWMTJJTHXAIUYLZCXZIXRBHVIUTBPHJOHPCOPTLMICULSTMUQFXIPUOFRBTZQPTHTUOJGOUMTJPBEBTUPTOHSGOHCOJTSBMUBXXIPUOVBOZQPTHTUOJJCBPBLOMMIBHTHPJBLRATVBHSOGIUTTJTGTHXOUQAIUYXRTLIJCXBIHIVMISTLOHSMBFRTULZQJICBLMLGOHLVBTJSGOMJTRILTJIHSIHARBMRXRTAUBXTUROLZTTHXIJSBLXIZTOVBULXEIJCGTOLXIOGTUBMOLMIHXUBZCXBIHATLTTGXIVBHSIHJQLGOJJZIIYLLCMROLMIJIHTJFOUYTURBXXLOZMIVLTMUTXAUBXBHPMIETUBHPXRUTTMBFRTULIUMIJIHTJRIQOUSJTQLQOUSJTQPUOGLXRTUTOUTRIATETUGOHQAIUYLARBMRSTOJGILXBHXTUTLXBHPJQABXRXRTOHOJQLBLOHSSTMUQFXGTHXIVLIGTIHTFOUXBMCJOUMBFRTUGILXIVXRTLTOUTLRIUXAIUYLFCZJBLRTSBHGOPOKBHTLIUBHMIUFIUOXTSBHXIZIIYLIVOPTHTUOJHOXCUTOHSHTOUJQOJAOQLXRTIHTMBFRTUSTOJXABXRBLXROXXQFTIVLBGFJTLCZLXBXCXBIHARBMROFFTOULABXRLTFOUOXTSAIUSLBHXRTFCKKJTLTMXBIHIVICUMCUUTHXGOPOKBHTLOHSHTALFOFTULIHTATJJYHIAHPTGIVMUQFXOHOJQLBLTDCOJXIOHQGISTUHLFTMBGTHMOHZTVICHSBHXRTLXIUQXRTPIJSZCPZQTSPOUOJJOHFITXRBLXIISTOJLABXRXRTLBGFJTLCZLXBXCXBIHMBFRTUNCLXUTVTUUTSXIZCXMIETULOMOLTBHARBMRAIUSSBEBLBIHLOUTOZLTHXFITROLOJLIJTVXCLOHTLLOQMOJJTSMUQFXIPUOFRQUILOUBIMOHSTJOLUTMTHXZIIYXRTGBJBXOUQMBFRTUIVMIGGOHSOHXZOKTUBTLLRIALXRTCHUOETJBHPIVIHTFOUXBMCJOUMUQFXIPUOGARBMRVIUGOHQQTOULROSZOVVJTSXRTZTLXTVVIUXLIVOJJOGOXTCULOHSBXBLUOXRTULCLFTMXTSIVLIGTVTAARIATUTHIXOGOXTCULXRTZIIYMIHXOBHLOMROFXTUIHPTHTUOJMUQFXOHOJQLBLOHSOJLILIGTMUQFXIPUOGLVIULIJCXBIHLTMUTXOHSCUPTHXZQVJTXMRTUFUOXXBLFUBGOUBJQORBLXIUQIVLTMUTXAUBXBHPOGILXBHXTUTLXBHPIHTZQXRTAOQZCXMIHXOBHLOJLIOHCGZTUIVTWOGFJTLIVMUQFXOHOJQLBLBXOJLILRIALOXOZJTARBMRXRTAUBXTUROLHTETUZTVIUTLTTHBHFCZJBLRTSVIUGOJBLXIVTHPJBLRXUBPUOGLXRUTTJTXXTULTDCTHMTLOHSXRTVUTDCTHMQABXRARBMRXRTQOUTCLTSBHXRTJOHPCOPTIXRTUTWOGFJTLIVSTMUQFXGTHXGOQZTVICHSBHXRTGOMZTXRXUOHLJOXBIHIVJOHPBTLPTHBOJJBXXJTZIIYSTJOMUQFXIPUOFRBTXRTOFFTHSBWXIXRBLXUOHLJOXBIHMIHXOBHLXRTMIETXTSFJOQVOBUSTGIHLXUOXBIHFUTFOUTSZQJBTCXTHOHXMIGGOHSTUAALGBXRIVXRTCHBXTSLXOXTLHOEQNCLXARQLIOZLIUZBHPOLCZNTMXROLZTTHLIHTPJTMXTSBHOAIUJSVCJJIVFCKKJTJIETULBLROUSXICHSTULXOHSTLFTMBOJJQLBHMTXRTOHOJQXBMAUBXTUBHOSSBXBIHXITHXTUXOBHGTHXROLLIGTXRBHPXIIVVTUIVOGIUTLTUBICLHOXCUT"
alphabet=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

cipher = cipher.lower()
# [index+1] -- to find the corresponding. plain+key % 26 - 1, something. then decr, 

def stream(cipher, key_len):
    streams = [""] * key_len
    index = 0

    for c in cipher:
        streams[index] += c
        index = (index + 1) % key_len
    # print(streams)
    return streams
    

# test all offsets and count matches. 
def offset(cipher):
    n = len(cipher)
    counts = []
    
    # set the n to maximum key length, maybe 50?
    for shift in range(1, 100):
        count = 0

        # cipher[i] is the shifted cipher
        # cipher[i+shift] is the original one. 
        # c0 c1 c2 c3 c4 | original starts on the shift index
        #    c0 c1 c2 c3 | shifted starts on index 0 of original.
        # we end on n-shift
        for i in range(n-shift):
            if cipher[i] == cipher[i+shift]:
                count += 1
        counts.append(count)

    print(counts)
    return counts

def print_offset(counts):
    plt.figure(figsize=(50, 4))
    plt.bar(range(len(counts)), counts)
    plt.xticks(range(len(counts)))

    plt.show() 

def freq(cipher):
    cipher = Counter(cipher).most_common()
    
    return cipher


def frequency(cipher):
    cipher = Counter(cipher).most_common()
    print(cipher)

    freqEnglish = {'e': 0.12702, 't': 0.09056, 'a': 0.08167, 'o': 0.07507, 'i': 0.06966, 'n': 0.06749, 
                's': 0.06327, 'h': 0.06094, 'r': 0.05987, 'd': 0.04253, 'l': 0.04025, 'c': 0.02782,
                'u': 0.02758, 'm': 0.02406, 'w': 0.02360, 'f': 0.02228, 'g': 0.02015, 'y': 0.01974, 
                'p': 0.01929, 'b': 0.01492, 'v': 0.00978, 'k': 0.00772, 'j': 0.00153, 'x': 0.00150,
                'q': 0.00095, 'z': 0.00074}

    letters = list(freqEnglish.keys())
    frequencies = list(freqEnglish.values())

    cipher_letters = [obj[0] for obj in cipher]
    cipher_frequencies = [obj[1] for obj in cipher]

    fig, axes = plt.subplots(2, 1, figsize=(20, 4))

    axes[0].bar(letters, frequencies, color='skyblue')
    axes[0].set_title('English Standard Frequency', fontsize=10)
    axes[0].set_xlabel('Letters', fontsize=10)
    axes[0].set_ylabel('Frequency', fontsize=10)
    axes[0].grid(axis='y', alpha=0.3)

    # Plot 2: Vowels only (sorted)
    axes[1].bar(cipher_letters, cipher_frequencies, color='lightcoral')
    axes[1].set_title('Stream 7', fontsize=10)
    axes[1].set_xlabel('Letters', fontsize=10)
    axes[1].set_ylabel('Frequency', fontsize=10)
    axes[1].grid(axis='y', alpha=0.3)

    plt.tight_layout()  # Adjust spacing between subplots
    plt.show()

def decrypt(key, cipher):
    plaintext = ""  

    for c in cipher:
        plaintext += alphabet[(alphabet.index(c)-key) % 26]
    return plaintext

def vig(keys, cipher):
    plaintext = ""  
    key_index = 0

    for c in cipher:
        plaintext += alphabet[(alphabet.index(c)-alphabet.index(keys[key_index % 6])) % 26]
        key_index += 1

    return plaintext

def ic(stream):
    counts = Counter(stream)
    length = len(stream)
    ic = 0.0

    for c in counts:
        ic += (counts[c] / length) * (counts[c] - 1) / (length - 1)

    # print(ic)
    return ic

def find_alph(a, b):
    return (alphabet[(alphabet.index(a) - alphabet.index(b)) % 26])

        
total_counts = offset(cipher)
print_offset(total_counts)

streams = stream(cipher, 26)
coinc = 0
for s in streams:
    coinc += ic(s)
    print("Average: ", coinc/len(streams))


for s in streams:
    print(freq(s))
    frequency(s)

"""

for i in range(2, 50, 1):
    streams = stream(cipher, i)

    print("Key Size:", i)

    frequency(streams[0])
    frequency(streams[1])


key_sizes = [41, 37, 26, 46, 14, 49]

print("IC of entire cipher: ", ic(cipher))

streams = stream(cipher, 41)
for s in streams:
    print(freq(s))
    frequency(s)



for k in key_sizes:
    streams = stream(cipher, k)
    print("Key size: ", k)

    for s in streams:
        print("  key letter")
        counts = freq(s)
        print(find_alph(counts[0][0], "e"))
        print(find_alph(counts[1][0], "t"))
        print(find_alph(counts[2][0], "a"))
        print(find_alph(counts[3][0], "o"))
        print(find_alph(counts[4][0], "i"))

"""
# frequency(streams[6])



keys = "semper"

#print(vig(keys, cipher))


"""
seed=123436  key=KASISKI  recovered=KASISKI  wrong=0  PASS
seed=123436  key=OZMSTVPRBNYJGHIFDULXCEAWQK  recovered=OZMSTVPRBNYJGHIFDULXCEAWQK  wrong=0  PASS
=== CIPHERTEXT CHALLENGE ===

--- Ciphertext 1 ---
DHWKZKVMEKIJOBRALBZSAVELBWBCGILPADAVOONJOYEEFKQBMZRWAWXBCYAVKYUOSMKZPWBMSBAYVKSSTDICVLQMLDGOTUEADPPOMZNYEOLKBWXBKTADWVGSSGTSDMNWWIJOVYWAVSZWCILQGXBYAHXDIXYIFBWBVYAFLLRQCWWUSILYBQZWDCBNAVYDWDHWKJIXDOYZSWIXDEIJUQXGXWJKBDEFBAYVOAUPSZXOAJIFMMYFWIURAEPHWKOLFOOMDDPSSAAMCCKLDGVYVOBQKABKVIFOWKKROFMOSBRAHMFMQVMSZCSVPIYIKWIVLDMLDMBVZIKCMBVWLLRMCAEMHEZZOKMSXLKFWEKOZSADVMWJORKPSFMLEWVSNLODXWJMWXVWVAOVMEGNJONORWVUOVYWDMLEAOXSUAXMPIYILKEKTUPAXODHWAEKTVVKEWPQXDSNSSZVYMVAPWBMVQKDZSBMBAYVYFNWOOTCEPKWZBPOJBZBMOLGVYCMQMWVLCJOGAVFSVQRWAHOKDINMDIIDTZMLRBRAFLLRTOTLMJCNYRUWFFMXIWVUOBREKMZKDOBWMFMWZIWLGEBKTTBZOBGOGNLRMCEOPAMPKRWTGXOORSVVDPORWNGBMWOKBDSSOLQBGMWXTSQFKBVESALYVOOXBZOUSSKQFQDYWWTKKZOBGBZPWENVBGRIFEAVUVCNEVHSXLTOXBZOAOTOWDOBDEJARSAYNWEZSKRWSAHBMFIGCKVGNIKKSBLODXZGWBREUMFDZKLKMUDQYNGNLRMRIYPXBMAUWVUIOBOMXVEZSNYWMBXBEDQESVKRQQFFMCTAOSDQYNWFSWQXIFOADIQAAVLYUKKWAMBMGEXQFNQDNGESCINOMJDOJOTOMWXBGOKCHZWCEVDGGMVSSVVRIFIFOLGWKDVQLSWXADKGXBKCLAOSBRSMXHYAODNWOOTCPGQFDMBSSVVLCDJOMXSVNHSAFODORUWFDIMTWLSXGCUHXGCMNVGEWVQDRWDWBAOSOQLRICUHXGCMNCGVKYVKNLIFNAROOASCUECZDSBQOTQIKMWELVJWOFZEUBWNWPADMLDMBAHXWKZSNYWFVGDHJMWDQWEKNAQCBESDNFDFVNDNFLZRWTAWQXAJGSCAEMHBAYVCYLMWKPYALPGOBROUWJBMMTAWFCGDOGIZOIDHWWLRMDOYWSRMKDLPWYBREJBZOIMCWXLKVMEGNBZZYVALWCNSVWWXDPOVGEWVAGILPXBMAUWVUSMCOXIFNIDOLIDYNYULWXKVOXHMUDMNIFIDYVQEJKJIXDOYZSWEOSZWMVLZRGJSLTILGWCPWBTZMKSFDHNWOOTKMGVYDPYSWTWDBORKPSFQXGSXHBWHIEILOTITZMUYZBEUBXBMAUWVUINYREICSVQUHBZOMHPWKLOLKSLWLRMZRWAWXBMAKMOOAROMTVRIFEFWLBWEBDMKOTOCLQFQQDFJWEDPOFADWVMDTWZKOOWEFBSDJLULBZSAGOMTVMIESWCKDWCPGBSVAYTZMKRWBTOWJNQXWZQURQDIKCKOLKNVWMBQWMWLAKBOCGVUOZXIKBZKBYFKXGDBSNYDGGMVSGVDIBRRGCYRBREAZCXWGNUPSBIMTWZACBSCKIKFWGEDAOOESLDIKCCWELPWXBRALBZOTKSLDGGMVCSVFYBLEXWMXLDHWVWHBCTWXVOUKNVALRIDWWIKCQQNLWLRMWOKBXBMAUWVLYNDHWAMZXYSWLNYEOLKBZODKLMMWGPSCZPSZXONKBGLMKWJWFQICSMUHDQYNUWFMMBNAVYDPSSABEKGLEOMDVBYRWXWKBREJMKYUOTZQFQERIUPZKAKLJMSNGLEWVKKQNIFLWKTSNYEADPDHWAAWXVEKBGPKBYHBGQZKMKBZOZOIKWXDMXAKPGBBNELWMBQXTGBJSIVAFLWBZYRSTKYBRESDWBIQEVMUBGZTGZSMKESLWEOLDOLPWGWBKSVVPCVLQIOKZOOXEZKBREEIQOFZEUBXBWWOFTQVMDTWZKYNDEPBOSTVUKCSVTIPSCKOIDTZQKZWSNLIFNUKKWAGWMPUJBZOZYBKMJFIDIGVKLMPOJMXSTVIFOAXIXYGNZSACUTALSBETAWFCPYWWDWBBREJMACDKLMMWFMXIFBZOUKKAVYYNGRGVYCCLSLQLEBSOFALRMKCLCSVXVAUQFQWPSMXHYAODHTSSVDEPBNKTEEKQFDPOIJAMZXYSWLHYASTAWFCXETKBZOXVAAVLOFDPGAKSJSLABAOALEXWJOCCIFDACCKLXWJWKKUKQFQCCTGVGDMOAKQDIBROKMNOZIPGQFDAPOJEZSKRTZMWHXORAMFMMNDWKJIXDOJMPKUSNWAAXINVSVUOIDCLPWXEOHSDWWINEGCJCCLSLQLEBSOFAOOPKVWIKCCWEVBZKBDHWUGCBPRWYMOVDVGEWVLSSJMHBMCEFBAXOOHSDAXOXOLMVDPOVNLAQZKMKLKFLFSOMZKDOSWTWMBODKZSDPORLPSXDKSLPWCCLSLQLEBOFGZSZZOFWZJSVQAVQYBIWOSLKDWKDAOJKUKONLLRQCLWINOADHWDGGMVOXAWMWXDXZWACONUGNDWBEHZWCMXTGBZSAGIDTUKCCELPWDPSRVWXDPOVNLAQZKMKDKDWBEHZWCMXTGMFYBPRWYMOVDBMBTOBDEJBZKVDHWLAQZKMSWHBMFIGCKVGWEFBAYVODBBZOVZRGJSLTIRWXJOAONLAAKVNUEIQBMZRWAWXBIAKBGMWXSGVSXBCWWPSFMKSKQYXMNTZMNKTEELBGDPOMGALPZOQMMFDWXEJIFNBREJMZKALEWVFYLSFXQUETDYAVANMXTANQSVQHAVLRMVELBWBSGHAKZDPBEWBAWMCHSAXYTVOOMVBJETGCJZZOSWVLMZIPLWYBIWIKBGYAROJBLYXBONQVOIXYUTWKZNIKBAXKDIGVSWWXGDMLDMBSOPAMPWIYPLBMZRWAWXBXRKEADPDHWAWFMXSMJKDQDULQGXAWAVMSCAROOVSDKXOLQUOPYWICAMSVYABTOKYMWAHYACITTWDWCPGBLRMSNUWFQZEILGGPAOQMMFMMCTZWEYZOTZIFYVMEAVSCPYRLBWHBGHAKZMWXTSQFCVYTSAAXOVEGKUEZBEFKWYNREGZZKVYTAKWKOKIFILNPYWICAMSVYLPWWMBEWFURIXGAVYYNDHWDSVCOSWIFNWGIDTTBQXGGCLGWBDKCYQMCTAWFCIDELPWPQBSLTAXMYFLPWMZIPLWYBIWIKZWZMKTWLSCQDWGCDNIZPWIJKNDEJBZOUKKAVYYNDHAAWHKRAFOWDPOBWOAXVSNYWXDPOMWAKKOOCSVSVUYSLJWBMKDLPWPQBSLEGBLKPHMSBADOTMFYBSFQNMBVSSZQFQBGOFMOCCLSLQLEBOSLPJOMWOJMUKVLEXCJXQCHWLAXBREKCYQMCTWLKOYEEFKWDWQOSPWKLGILPSXLREJMLRMGOJLOSBRWGCDNJOTJQWNQXAFGUKAOBWKSEAOILQKKKYMEWFGWBDSVVLMMAMAWDPOFJMIEMXCQWXDPOLWBLOZZIKAMQOOSLQNOWPWSZJSDODSBLRQCPGQFDEOBWOAXBYNGBAMMZALBWBVCPGALZWXEUWMXKSLSKUYCXTEILDMBAFLKYWXSGBZKBDHWZWCBYFLPWCWVULQGXQCLSZYOTIAEILDMBOXNAVTSNYQFPZKMWEGBSSNLPWQQFEFMPKUZLWQLGWELVIDCWLEFWLSKODLPSDNKNVVZKDORWAMVBODXZGWZOCAXJYKKLWVUSXREJUWXBDHAAEKGXOLJWDPOCSAWGQDHGBZOZVELBWBALULQLZZOSWVLCIZOKAALQVILGORQMHAASVEKYKEWVTGOJBZSVFEKBAQIDIFOSLKNEXOZSRULEVGZYBSLCNGFIZSITLKMDVMWPNCGYMZRKSIGRBXSUDDTLRMNIYZSWAYLMBAYVWELPGN

--- Ciphertext 2 ---
MIGFBJTSZQVUOHYUVUOFUBTOVXTUXRTUTLXIVXRTZIIYROSZTTHMIGFJTXTSXRTHBHTXQTBPRXGILXVUTDCTHXTHPJBLRXUBPUOGLMIGZBHBHPOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRBLXOZJTOHSXRTVIJJIABHPIHTOUTHIXUTVTUUTSXIBHXRTXTWXROEBHPZTTHMIGFBJTSLBHMTXRTMIGFJTXBIHIVXRTZIIYXRTIHTRCHSUTSOHSHBHTGILXVUTDCTHXTHPJBLRSBPUOGLMIGFBJTSVUIGOMICHXIVXUBPUOGLZQVJTXMRTUFUOXXBHLTMUTXOHSCUPTHXLCFFILTSHIXXIBHMJCSTIETUJOFLZTXATTHAIUSLOHSZQVUOHYUVUOFUBTBHMJCSBHPIETUJOFLXRTIUBPBHOJVBPCUTLATUTGOSTABXROXQFTAUBXTUOHSXRTHJBHTLOUUIALIUMBUMJTLATUTOSSTSXRBLVBJTUTFUISCMTLXRTGOLATJJOLBLFILLBZJTOLFJOBHXTWXFJTOLTLTTXRTRXGJETULBIHBVQICABLRXILTTXRTVBPCUTLABXROJJIVXRTBUSTXOBJLGBHIUMIUUTMXBIHLLCMROLUTGIEBHPTWXUOLFOMTLIUFCHMXCOXBIHIUOSSBHPGBLLBHPLFOMTLIUFCHMXCOXBIHIUSBOMUBXBMOJGOUYLATUTGOSTABXRICXHIXTOUMROBMOHSBHMIHLBLXTHXLFTJJBHPAOLUTXOBHTSBHXAIFJOMTLXRTHCGZTUIVOUTVTUTHMTSVBPCUTAOLMIUUTMXTSPUOGGOUOHSLFTJJBHPATUTIHJQMIUUTMXTSOLBHXRTVIJJIABHPJBLXIVHIXOZJTMROHPTLBHMROFXTUBBBATBXOJBMBKTSXRTVBULXIMMCUUTHMTIVGOPBMLDCOUTZTMOCLTBXLTTGTSJBYTXRTOCXRIULBHXTHXBIHBHXRTLOGTMROFXTULOBSZTMJIMYABLTAOLMIUUTMXTSXILOBSXIZTMJIMYABLTLIGTMIUUTMXBIHLATUTGOSTXIXRTTWTUMBLTLBHIUSTUXIUTMXBVQXRTLFTJJBHPBHXRTBUFJOBHXTWXLIUBHIHTMOLTXIUTLIJETOHBHMIHLBLXTHMQBHBXLYTQBHTWTUMBLTLTETHJTXXTULATUTGBLLBHPXRTCHMIUUTMXTSMUQFXIPUOGBLEBHLMVTOTIIRLTVRJTRCHLXHMJXLJMBOTLRURLBUTUGXLTXTFSXIBHGUXXRXXJUCZTATABLRXIXROHYXRTOHIHQGICLFUIIVUTOSTULARIEIJCHXTTUTSOXXRTZUBXBLRHOXBIHOJMBFRTUMROJJTHPTAAAMBFRTUMROJJTHPTIUPXRTAIUSMUQFXIPUOFRQFUIFTUJQLFTOYBHPTGZUOMTLXRTTHXBUTVBTJSIVLTMUTXAUBXBHPARBJTXROXZUOHMRIVXRTLCZNTMXSTOJBHPABXRXRTLIJCXBIHOHSUTOSBHPIVMUQFXBMGTLLOPTLBLPTHTUOJJQUTVTUUTSXIOLMUQFXOHOJQLBLAIUYLIHXRTLCZNTMXIVLTMUTXAUBXBHPOUTMIGFOUOXBETJQHCGTUICLBVHIXOJAOQLTOLBJQOEOBJOZJTZCXAIUYLSTEIXTSFCUTJQXIXRTOHOJQLBLIVLCMRAUBXBHPOHSXRTLIJEBHPIVBXLMUQFXIPUOGLROETCHXBJUTMTHXJQZTTHLIUOUTOLXIZTOJGILXHIHTWBLXTHXVIUXRTPTHTUOJUTOSTUXISOQATROETXAIFOUXBMCJOUJQTWMTJJTHXAIUYLZCXZIXRBHVIUTBPHJOHPCOPTLMICULSTMUQFXIPUOFRBTZQPTHTUOJGOUMTJPBEBTUPTOHSGOHCOJTSBMUBXXIPUOVBOZQPTHTUOJJCBPBLOMMIBHTHPJBLRATVBHSOGIUTTJTGTHXOUQAIUYXRTLIJCXBIHIVMISTLOHSMBFRTULZQJICBLMLGOHLVBTJSGOMJTRILTJIHSIHARBMRXRTAUBXTUROLZTTHXIJSBLXIZTOVBULXEIJCGTOLXIOGTUBMOLMIHXUBZCXBIHATLTTGXIVBHSIHJQLGOJJZIIYLLCMROLMIJIHTJFOUYTURBXXLOZMIVLTMUTXAUBXBHPMIETUBHPXRUTTMBFRTULIUMIJIHTJRIQOUSJTQLQOUSJTQPUOGLXRTUTOUTRIATETUGOHQAIUYLARBMRSTOJGILXBHXTUTLXBHPJQABXRXRTOHOJQLBLOHSSTMUQFXGTHXIVLIGTIHTFOUXBMCJOUMBFRTUGILXIVXRTLTOUTLRIUXAIUYLFCZJBLRTSBHGOPOKBHTLIUBHMIUFIUOXTSBHXIZIIYLIVOPTHTUOJHOXCUTOHSHTOUJQOJAOQLXRTIHTMBFRTUSTOJXABXRBLXROXXQFTIVLBGFJTLCZLXBXCXBIHARBMROFFTOULABXRLTFOUOXTSAIUSLBHXRTFCKKJTLTMXBIHIVICUMCUUTHXGOPOKBHTLOHSHTALFOFTULIHTATJJYHIAHPTGIVMUQFXOHOJQLBLTDCOJXIOHQGISTUHLFTMBGTHMOHZTVICHSBHXRTLXIUQXRTPIJSZCPZQTSPOUOJJOHFITXRBLXIISTOJLABXRXRTLBGFJTLCZLXBXCXBIHMBFRTUNCLXUTVTUUTSXIZCXMIETULOMOLTBHARBMRAIUSSBEBLBIHLOUTOZLTHXFITROLOJLIJTVXCLOHTLLOQMOJJTSMUQFXIPUOFRQUILOUBIMOHSTJOLUTMTHXZIIYXRTGBJBXOUQMBFRTUIVMIGGOHSOHXZOKTUBTLLRIALXRTCHUOETJBHPIVIHTFOUXBMCJOUMUQFXIPUOGARBMRVIUGOHQQTOULROSZOVVJTSXRTZTLXTVVIUXLIVOJJOGOXTCULOHSBXBLUOXRTULCLFTMXTSIVLIGTVTAARIATUTHIXOGOXTCULXRTZIIYMIHXOBHLOMROFXTUIHPTHTUOJMUQFXOHOJQLBLOHSOJLILIGTMUQFXIPUOGLVIULIJCXBIHLTMUTXOHSCUPTHXZQVJTXMRTUFUOXXBLFUBGOUBJQORBLXIUQIVLTMUTXAUBXBHPOGILXBHXTUTLXBHPIHTZQXRTAOQZCXMIHXOBHLOJLIOHCGZTUIVTWOGFJTLIVMUQFXOHOJQLBLBXOJLILRIALOXOZJTARBMRXRTAUBXTUROLHTETUZTVIUTLTTHBHFCZJBLRTSVIUGOJBLXIVTHPJBLRXUBPUOGLXRUTTJTXXTULTDCTHMTLOHSXRTVUTDCTHMQABXRARBMRXRTQOUTCLTSBHXRTJOHPCOPTIXRTUTWOGFJTLIVSTMUQFXGTHXGOQZTVICHSBHXRTGOMZTXRXUOHLJOXBIHIVJOHPBTLPTHBOJJBXXJTZIIYSTJOMUQFXIPUOFRBTXRTOFFTHSBWXIXRBLXUOHLJOXBIHMIHXOBHLXRTMIETXTSFJOQVOBUSTGIHLXUOXBIHFUTFOUTSZQJBTCXTHOHXMIGGOHSTUAALGBXRIVXRTCHBXTSLXOXTLHOEQNCLXARQLIOZLIUZBHPOLCZNTMXROLZTTHLIHTPJTMXTSBHOAIUJSVCJJIVFCKKJTJIETULBLROUSXICHSTULXOHSTLFTMBOJJQLBHMTXRTOHOJQXBMAUBXTUBHOSSBXBIHXITHXTUXOBHGTHXROLLIGTXRBHPXIIVVTUIVOGIUTLTUBICLHOXCUT
"""
